spring:
  application:
    name: share
project:
  version: @project.version@
server:
  webflux:
    base-path: /api

springdoc:
  show-actuator: true
  swagger-ui:
    path: /api/swagger-ui.html

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include: health,info,metrics
